const questions : string[][] = [
  ['If you could have an extra hour of free time every day, how would you use it?', 'time'],
  ['What was your favorite holiday you ever went on?', 'travel'],
  ['If you could only listen to one album for the rest of your life, what would it be?', 'music'],
  ['If you had to spend a million dollars in a day, what would you spend it on (no investments)?', 'money'],
  ['What was the worst job you ever had?', 'work'],
  ['What is a book you recently (or ever) read that you particularly enjoyed?', 'book'],
  ['What is your favorite city and why?', 'city'],
  ['What’s your favorite memory from your teenage years?', 'teenager'],
  ['What is your all-time favorite TV series?', 'TV'],
  ['Where did you go to college / school / uni and what did you study?', 'school'],
  ['What’s your favorite meme?', 'meme'],
  ['What does your morning routine look like?', 'morning'],
  ['Are you an early bird or a night owl?', 'owl'],
  ['What’s your favorite way to get in some exercise?', 'sport'],
  ['What is your most used emoji?', 'emoji'],
  ['If you had entrance music like a wrestler, what song would it be?', 'wrestler'],
  ['What is your favorite / guilty pleasure karaoke song?', 'karaoke'],
  ['What was your favorite food as a kid?', 'food'],
  ['If you had to delete all but 3 apps from your smartphone, which ones would you keep?', 'smartphone'],
  ['Which superpower would you like to have and why?', 'superhero'],
  ['What’s your favorite (local) tradition or holiday?', 'holiday'],
  ['If you had a time machine, what time would you like to visit (past or future)?', 'time'],
  ['What fictional world or place would you like to visit?', 'world'],
  ['Where did you go on your last trip?', 'travel'],
  ['Do you play (or have you played) any musical instruments, and which?', 'instrument'],
  ['What is your favorite meal to cook and why?', 'cooking'],
  ['What’s your best scar story?', 'scar'],
  ['What’s your favorite fruit or vegeable?', 'fruit'],
  ['What’s your favorite sandwich topping', 'sandwich'],
  ['If you could see one movie again for the first time, what would it be and why?', 'movie'],
  ['Is there any country or place you would love to visit, but haven’t yet?', 'travel'],
  ['If you had to teach a class on one thing (non tech-related), what would you teach?', 'class'],
  ['What is the weirdest thing in the room with you right now?', 'room'],
  ['What was the last thing that you ate?', 'eating'],
  ['What is your best tourist recommendation for the city/area you live in?', 'city'],
  ['What is your favorite dessert?', 'dessert'],
  ['What was your favorite game to play as a kid?', 'children'],
  ['What was your first online screen name / handle?', 'screen'],
  ['What’s something you’re looking forward to, and why?', 'happy'],
  ['Do you work better with or without music? What are you listening to while you work?', 'headphones'],
  ['What’s one productivity tool you couldn’t live without, and what makes it indispensable?', 'computer'],
  ['What do you like best about your current workspace?', 'desk'],
  ['What’s something from your childhood that you still love today?', 'children'],
  ['What’s normal where you live, but might seem weird to the rest of the world?', 'country'],
  ['What was the first concert or gig you ever attended?', 'concert'],
  ['What’s something you do to relieve anger or stress?', 'stress'],
  ['Where do you want to retire?', 'old'],
  ['What’s your current cellphone wallpaper?', 'smartphone'],
  ['What’s your favorite breakfast food', 'breakfast'],
  ['What’s the weirdest food you’ve ever eaten?', 'food'],
  ['What’s the most memorable restaurant you’ve been to?', 'restaurant'],
  ['What was the last hobby you picked up?', 'hobby'],
  ['Is there any TV show you’ve been watching regularly or recently?', 'tv'],
  ['What movie did you recently watch that you liked?', 'movie'],
  ['What do you usually get up to on the weekends?', 'weekend'],
]

export default questions;